### ISSUE TITLE
Is there a setting that turns off Private Messaging?

### ISSUE THREAD

**Issue by BobWalsh** [thredded/thredded#583]
... we love the rest of thredded, but for our needs we want to turn off private messaging for now. Is there an easy way of doing this? Or even a hard way?

**Comment by jayroh** [comment]
You could probably overwrite the views that link to those sections. I think
that's how I would approach it considering there is no setting (currently)

**Comment by timdiggins** [comment]
and once #614 is part of your version (on merge/release) you can add

```css
li. thredded--user-preferences--notifications-for-private-topics {
    display: none
}
```

and there will be no display of private messaging at all
