### ISSUE TITLE
Global preferences page when many messageboards

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#621]
I like #581 and can see the point. It does cause quite a big page when you have lots and lots of messageboards. Not yet sure what the answer is yet -- but probably can only be handled by mainapp (e.g. some messageboard lifecycle to remove inactive ones from the default view, or other way to reduce to smaller number of messageboards by some order and limit). 

FYI @glebm  Am just now catching up on thredded after a long break (impressive progress by the way!).

**Comment by glebm** [comment]
The list of messageboards is provided to the UI by [UsersPreferencesForm#messageboards](https://github.com/thredded/thredded/blob/master/app/forms/thredded/user_preferences_form.rb) which the main app could override to do the sorting / filtering.

The view for that list is here:

https://github.com/thredded/thredded/blob/07218a43c850bb0a654a82ccf0f8c19910132c4e/app/views/thredded/preferences/_messageboards_nav.html.erb#L1-L8

> It does cause quite a big page when you have lots and lots of messageboards

I'm curious, how many are there? If their names are short, perhaps you could mitigate it on desktop by increasing the number of messageboards per row to 3 like this:

```scss
@include thredded-media-desktop-and-up {
  .thredded--preferences--messageboards-nav {
    &--item,
    .thredded--messageboards-group::after,
    .thredded--messageboards-group::before {
      flex-basis: ($thredded-grid-container-max-width / 3);
    }
  }
}
```
