### ISSUE TITLE
Accessibility for screen readers ?

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#762]
I was trying to add a screen-reader only text for Follow/Unfollow buttons (actually in thredded-workgroup, but it made me think about thredded).

We don't seem to have a screen-reader only class, and some of our icon-only buttons don't have screen reader text (maybe they all have title attributes or something else -- I haven't checked).

Screen-reader only text is so useful for tests also (and making sure the tests use text is a way to ensure accessibility).

Should we add one -- something like (copying from bootstrap):

```css
.thredded--sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0,0,0,0);
  border: 0;
}
```
